---
- name: Install Logstash
  apt:
    name: logstash
    state: present
  when: ansible_distribution == 'Ubuntu'

- name: Install Logstash
  yum:
    name: logstash
    state: present
  when: ansible_distribution == 'CentOS'
